---
apiVersion: v1
kind: Secret
metadata:
  name: storageos-api
  namespace:  devops
  labels:
    app: storageos
    chart: storageos-0.1.0
    heritage: Tiller
    release: storageos
type: "kubernetes.io/storageos"
data:
  # apiAddress: "aHR0cDovL3N0b3JhZ2Vvczo1NzA1"
  apiAddress: "c3RvcmFnZW9zOjU3MDU="
  apiUsername: "c3RvcmFnZW9z"
  apiPassword: "c3RvcmFnZW9z"