---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        proxy . /etc/resolv.conf {
            except ct.csii.com.cn
        }
        file /data/ct.csii.com.cn ct.csii.com.cn
    }
  Csiifile: |
    $TTL 10
    @     IN  SOA     ns1.cznews.cc. root.cznews.cc. (
                2   ;serial
                300 ; refresh
                1800 ; retry
                10  ; expire
                300 ; minimum
    )

    ;name servers
    @       IN      NS      ns1.cznews.cc.
    ns1.cznews.cc.    IN  A 47.92.154.72
    cc    IN  CNAME    www.baidu.com.  
    gitlab    10 IN A 172.16.45.141
    harbor    10 IN A 172.16.45.141
---
apiVersion: v1
kind: Service
metadata:
  name: coredns
  labels:
    app: coredns
spec:
  selector:
    app: coredns
  clusterIP: 10.3.0.53
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coredns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
      - name: coredns
        image: registry.ispacesys.cn/k8s/coredns:1.0.6
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        - name: data-volume
          mountPath: /data          
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
        - name: data-volume
          configMap:
            name: coredns
            items:
            - key: Csiifile
              path: ct.csii.com.cn              