apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
spec:
  rules:
  - host: gitlab.ct.csii.com.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80