kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone-server
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 2Gi