---
apiVersion: v1
kind: Service
metadata:
  name: drone-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: drone-server
  ports:
  - name: http
    port: 8000  
  - name: grpc
    port: 9000