---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-prometheus-alertmanager
  namespace: monitoring
spec:
  rules:
  - host: alertmanager.wodcloud.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kube-prometheus-alertmanager
          servicePort: 9093