---
kind: Service
apiVersion: v1
metadata: 
  name: prometheus-out
  namespace: monitoring
  labels: 
    kubernetes.io/name: "Prometheus"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec: 
  type: NodePort
  ports: 
    - name: http 
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector: 
    app: prometheus

---
kind: Service
apiVersion: v1
metadata: 
  name: alertmanager-out
  namespace: monitoring
  labels: 
    kubernetes.io/name: "alertmanager"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec: 
  type: NodePort
  ports: 
    - name: http 
      port: 80
      protocol: TCP
      targetPort: 9093
  selector: 
    app: alertmanager
