---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hostpath-provisioner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hostpath-provisioner
  labels:
    k8s-app: hostpath-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: hostpath-provisioner
  namespace: default
---
kind: Pod
apiVersion: v1
metadata:
  name: hostpath-provisioner
spec:
  containers:
    - name: hostpath-provisioner
      image: registry-vpc.cn-qingdao.aliyuncs.com/wod/hostpath-provisioner:latest
      imagePullPolicy: "IfNotPresent"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName    
        - name: PV_DIR
          value: /data/hostpath-provisioner
      volumeMounts:
        - name: pv-volume
          mountPath: /data/hostpath-provisioner
  volumes:
    - name: pv-volume
      hostPath:
        path: /data/hostpath-provisioner
  serviceAccountName: hostpath-provisioner
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hostpath
provisioner: hostpath