name: drone
version: 0.8.4
description: drone
appVersion: 0.8.4
apiVersion: v1
keywords:
- drone
home: https://drone.io/
sources:
- https://github.com/drone/drone
maintainers:
- name: mengkzhaoyun
  email: mengkzhaoyun@gmail.com
