---
kind: Service
apiVersion: v1
metadata:
  name: grafana
spec:
  selector:
    k8s-app: influxGrafana    
  ports:
    - protocol: TCP
      port: 3280
      targetPort: 8083
  externalIPs:
  - 192.168.13.40