apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-conf
  namespace: {{ .Release.Namespace }}
data:
  config: |
    [
      {
        "name": "KUBERNETES_SERVER_ALIYUN",
        "value": "https://172.31.14.41:6443"
      },{
        "name": "KUBERNETES_CERT_ALIYUN",
        "value": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDK1RDQ0FlR2dBd0lCQWdJSkFJQWVDWDZHdnRUS01BMEdDU3FHU0liM0RRRUJDd1VBTUJJeEVEQU9CZ05WDQpCQU1NQjJ0MVltVXRZMkV3SUJjTk1UWXhNVEl4TURZME5URTJXaGdQTWpFeE5qRXdNamd3TmpRMU1UWmFNQkl4DQpFREFPQmdOVkJBTU1CMnQxWW1VdFkyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCDQpBUURZS2IvV1hwaW0xVlpDc2Z3Y1I5aDRzVEJFM2M4SWxORWtnNFhyUElIM1RES0VsWDdiR1B0Uk4yVldMNjlSDQpJQjJlZVFNVHFOZ3k2WW5aR1JqSjBVb1RBanoyWUUvUXQ4TmRscjJJRFRwQndleGE1Tk41enpnWDQ0UmR3WVRGDQo3cUk5NG5rWE5ZUFhhQkg1Wm5yRXpRZm52dHJNQXg2eG96L0lzRmVMc3Uza2M4Sm1NeDZzeFVKZkdLWCtoNlZVDQpsajNFeEUvSk9ITTlpLzIyZnRYdXJmeVYwbjV2S0Z0UldTeUFuVm53YVFIeThFcW0wdHBEaWlIZWRtUWI3MWx2DQpHOUs4RG9yQWI3dWVJZjFXWUVYTkRFQ3ZCajNja0VWTkVRU3JCcmZMY1pQL2RvSitpblcvL0FXOFVlYjRqcVNDDQo2VVVWalVwTUdORE5kOHk0YlZYaHV6S1RBZ01CQUFHalVEQk9NQjBHQTFVZERnUVdCQlQ2b05pUGNtQ1dwbkxBDQpJYUJ0R2xEQTFGcnM4REFmQmdOVkhTTUVHREFXZ0JUNm9OaVBjbUNXcG5MQUlhQnRHbERBMUZyczhEQU1CZ05WDQpIUk1FQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUIwNm1LYWQ0V0VhOTVuRmpUSjFXR3l5Wnh6DQpXcC81bUkvRXRkRkNsbTFudnhTQVJWcHJwMWoyVHU2Z1FUMnE0UlJWdWU5RHlBalpOZk45TndqTkVyYjdoenB0DQpleUVOTUpCTDFlOTIvSDkwQVdxNGpCRXhDWFE2MkV3QUd5eG5GZnRkQTUwWDNrN295cW5VdDFhdE5pNWFiOThFDQpjamMxMDRnbnRIc1ByMU1vRW9hUm9yRi93dGdwSGVqeW45cVZJcWY2ckxBby9rQ0RPVGJMcElmeHBoSkFBWG9iDQp3SmxjSkNIY09mTzhXRThFd3NwUU1WdWw1bFFYbUFmdTh6U1FLV3J0VjRhcjJDSEN3OEZFZDJhNkNCZHp5UGdDDQpXL0ZDZi9WM012ME9KVForTS9TZHcvWUZmdXpKUy9TMDNkY3RZdCtQejFUOWJvMkowZHpteTBmZDBIbjANCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg=="
      },{
        "name": "KUBERNETES_TOKEN_ALIYUN",
        "value": "7176d48e4e66ddb3557a82f2dd316a93"
      }
    ]