---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.fullname" . }}-redis
spec:
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: redis
  type: NodePort    
  ports:
  - name: redis
    port: 6379