---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
- kind: ServiceAccount
  name: traefik
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: kube-system
---  
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    [entryPoints.traefik]
      address = ":8380"     
    [websocket]
      protocol = "http"
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]        
    [accessLog]
      format   = "json"
    [api]
      entryPoint = "traefik"
      dashboard = true
    [acme]
      email = "mengkzhaoyun@gmail.com"
      storage = "acme.json"
      entryPoint = "https"
      [[acme.domains]]
        main = "wodcloud.com"
        sans = ["k8s.wodcloud.com", "grafana.wodcloud.com"]
    [acme.httpChallenge]
      entryPoint = "https"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik
  namespace: kube-system
  labels:
    k8s-app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik
  template:
    metadata:
      labels:
        k8s-app: traefik
        name: traefik
    spec:
      serviceAccountName: traefik
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        configMap:
          name: traefik-conf    
      containers:
      - image: hub.c.163.com/mengkzhaoyun/public:traefik-1.6.5-alpine
        name: traefik
        volumeMounts:
        - mountPath: "/config"
          name: "config"
        ports:
        - containerPort: 443
          hostPort: 443
          name: https
        - containerPort: 80
          hostPort: 80
          name: http
        - containerPort: 8380
          hostPort: 8380
          name: admin           
        args:
        - --configfile=/config/traefik.toml
        - --kubernetes