---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.NameSpace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: {{ .Release.Name }}
    port: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh
  namespace: {{ .Release.NameSpace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
  - name: {{ .Release.Name }}-ssh
    port: 22
    targetPort: 22
    nodePort: {{ .Values.gitlab.sshport }}
    protocol: TCP    