apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-postgresql
spec:
  selector:
    app: {{ .Release.Name }}-postgresql
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP  