kind: Service
apiVersion: v1
metadata: 
  name: grafana-out
  namespace: kube-system
spec: 
  type: NodePort
  ports: 
    - name: http 
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector: 
    k8s-app: grafana
